let array=[1,2,3,4,5,6]
console.log(array)
array.push(7,8,9,10)
console.log(array)
array.push(11,12,13,14,15)
console.log(array)
array.pop()
console.log(array)
array.pop()
console.log(array)
array.shift()
console.log(array)
array.shift()
console.log(array)
array.push(14,15)
console.log(array)
array.unshift(1,2)
console.log(array)
let a2=[16,17,18]
array=array.concat(a2)
console.log(array)
let s=array.join()
console.log(s)
array.reverse()
console.log(array)
array.reverse()
console.log(array)
console.log(array.indexOf(4))
console.log(array.indexOf(7))
console.log(array.slice(2,8))
array.splice(0,0,0)
console.log(array)
// array.splice(4,3,55,33,22)

console.log(array)